# Configuration:
exclude: ["CNAME", "README.md"]
permalink: /:year/:month/:day/:title
excerpt_separator: "<!-- break -->"

# Metadata:
title: Regent
author:
  name: Stanford University

# Navigation menu items. (Note that these a preceded by some fixed
# items coded directly in _includes/navbar.html .)
navigation:
  - label: Try Online
    url: "http://try.regent-lang.org/"
    external: true
  - label: Install
    url: "/install"
  - label: Reference
    url: "/reference"
  - label: Paper
    url: "/images/regent2015.pdf"

# Content configuration defaults:
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_title: true
      sidebar: true
      highlight_first: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_title: true
      sidebar: true
      highlight_first: false
